[build]
  functions = "./functions"
  build = "npm run functions:build && npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"
    X-Api-Key = "some-api-key-string"
    
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200